name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.5.6
homepage: https://flyer.chat

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.0.1
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  flutter_chat_types: ^3.3.4
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
